<!-- GEGY -->


<a name="Gegy"><h3>Gegy.com - Application Service Provider Model </h3></a>
<B>Description</b><BR>

<P>

The now defunct Gegy had an aggregation style business plan, with the
goal of easily connecting many small scale sellers with wholesale 
distributors.  Gegy provided a system for placing orders, made creating an online
store easy, provided tools 
for sellers (such as bulk order processing), and provided support for buyers and sellers.

<center>
<img src="images/gegyAggregate.gif" border=0><BR>
Gegy Aggregation Business Model
</center>
</P>
<BR>
<p>

Three distinct web sites were built: an administration site for internal use,
a Gegy portal for sellers, and a support site for shipping errors and 
returning merchandise.

<center>
<img src="images/gegyArch.gif" border=0><BR>
Gegy Architectural Overview 
</center>
<BR><BR>
I participated in development of the web-based front end, took on 
responsibilities for daily operations after deployment and made 
considerable contributions to the automation of the back-end. Eventually, in
varying degrees, I became familiar with every facet of the system.
</P>
<BR>

