<!-- ADDRESS BOOK -->

<HR>
<a name="address_book"><h3>Address Book - Mozilla Application</h3></a>
<B>Description</B>
<BR>
<P>
<a href="http://www.mozilla.org" target="_blank">
Mozilla</a> is more than a web browser, it provides a cross-platform framework for 
developing applications.  OEone (now Axentra) produced an operating environment which leveraged
Mozilla to create their Homebase software. The operating environment, Homebase,
contained many components including an 
Address Book, Web Browser, Calendar, Email, File Manger, and Word Processor.  
</P>

<center><img src="images/addressbook.jpg"><BR>
 Screenshot of address book
</center>

<p>As a member of the Address Book team I collaborated with other team members and the user 
interface group. Since Mozilla is an ongoing open source project, documentation for API interfaces was sometimes
incomplete.  Working on the Address Book required reading mozilla source code when
documentation was unavailable. It was therefore, on occasion, necessary to read XPCOM C++ code to 
write javascript.  The main elements of programming included XUL, javascript and CSS; the development
operating system was RedHat Linux.
</p>

<center><img src="images/mozilla_arch.jpg"><BR>
Mozilla Architecture<SUP>2</SUP>
</center>
<BR>
<B>Development Activities</b>
<UL>
	<LI> Team Collaboration
	<LI> Participation in a large project
	<LI> Code reading
	<LI> Use of many open source software tools (i.e. CVS, bugzilla )
</UL>


<BR><BR>
2.  Diagram based on
<a href="http://www.mozilla.org/docs/xul/xulnotes/moz_xp.gif" target="_blank">
http://www.mozilla.org/docs/xul/xulnotes/moz_xp.gif
</a>
<BR><BR>
