<!-- TIMESHEET -->

<HR>
<a name="timesheet"><h3>Timesheet - Web-based Application</h3></a>
<B>Description</b><BR>
<P> 
Created for tracking employee time on projects, the Timesheet application 
was built with iNet Developer (a Pictorius product for building intranet sites
collaboratively) and aided in testing new iNet features and 
uncovering defects.  iNet Developer was the flagship product
for Pictorius at the time and was built on top of Prograph, another Pictorius
product, an object oriented visual programming language.  Server side logic
was written with Prograph, a novel and enjoyable language to code with.
</P>

<BR>
<center><img src="images/prograph.gif"><BR>
Sample Prograph Code
</center>
<BR>

<p>

I participated in the application specification and design, after which,
I was responsible for 
maintaining documentation and was the developement lead for the project, which 
had two major releases.
After the first version was released and used internally, employee feedback was 
collected to improve and release a second version.  
</P>
<BR><BR>
<center><img src="images/timesheet_50.jpg"><BR>
Screenshot of main page
</center>
<B>Features</b>
<UL>
	<LI> Security
	<LI> Automated reminders 
	<LI> Session timeouts	
	<LI> Administration pages
	<LI> Reporting 
</UL>
<BR>
<center><img src="images/timesheet_arch.jpg" border=0><BR>
 Timesheet architecture and data flow
</center>
<BR>
<BR>

<!-- http://www.intranetjournal.com/reviews/inetdev20.shtml -->