<!-- SURROUND PHOTO -->

<HR>
<a name="surround_photo"><h3>Surround Photo - Application Maintenance ( C++ )</h3></a>
<B>Description</B>
<BR>
<P><QUOTE>"The VR technology built into Apple's QuickTime software makes it possible for
anyone to create, view, and navigate 360-degree panoramic images. Shooting such 
images, though, usually involves wide-angle lenses, special tripod mounts, and a 
time-consuming setup and shooting procedure." </QUOTE> <SUP>1</SUP>
</P>
<p>Surround Photo makes creating 360-degree panoramas 
quick and easy.  It uses a concave 360-degree mirror that attaches to most
consumer camera lenses.  Taking a picture creates a "donut" image which can then 
be converted to a panoramic image.
</p>
<center><img src="images/sp_mirror.jpg"><BR>
360-degree mirror
</center>

<p>Surround Photo has both Windows and Macintosh versions.  I was brought on-board the 
Surround Photo development team to fix defects and add new features to the Macintosh 
version of the product. My duties included finding and fixing "show stopper"
memory leaks, and Carbonizing the application.</P>

<center><img src="images/Surround_Photo.jpg"><BR>
Surround Photo screenshots
</center>
<BR>
<B>Tasks</b>
<UL>
	<LI> Tested application for defects
	<LI> Fixed defects
	<LI> Carbonized application <BR>(Modifying the application so it will run natively in Mac OS X)
</UL>


<BR><BR>
1.  Long, Ben. One-Shot VR Panorama Systems. <BR>
<a href="http://www.macworld.com/2002/10/reviews/panorama/" target="_blank">
http://www.macworld.com/2002/10/reviews/panorama/
</a>
<BR><BR>
